package mx.edu.utez.entity;
// Generated 21-jun-2018 22:32:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aplicacion generated by hbm2java
 */
public class Aplicacion  implements java.io.Serializable {


     private Integer idAplicacion;
     private Examen examen;
     private Usuario usuario;
     private double calificacion;
     private Set<Respuestausuario> respuestausuarios = new HashSet<Respuestausuario>(0);

    public Aplicacion() {
    }

	
    public Aplicacion(Examen examen, Usuario usuario, double calificacion) {
        this.examen = examen;
        this.usuario = usuario;
        this.calificacion = calificacion;
    }
    public Aplicacion(Examen examen, Usuario usuario, double calificacion, Set<Respuestausuario> respuestausuarios) {
       this.examen = examen;
       this.usuario = usuario;
       this.calificacion = calificacion;
       this.respuestausuarios = respuestausuarios;
    }
   
    public Integer getIdAplicacion() {
        return this.idAplicacion;
    }
    
    public void setIdAplicacion(Integer idAplicacion) {
        this.idAplicacion = idAplicacion;
    }
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public double getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(double calificacion) {
        this.calificacion = calificacion;
    }
    public Set<Respuestausuario> getRespuestausuarios() {
        return this.respuestausuarios;
    }
    
    public void setRespuestausuarios(Set<Respuestausuario> respuestausuarios) {
        this.respuestausuarios = respuestausuarios;
    }




}


