package mx.edu.utez.entity;
// Generated 21-jun-2018 22:32:54 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Examen generated by hbm2java
 */
public class Examen  implements java.io.Serializable {


     private Integer idExamen;
     private Categoria categoria;
     private Usuario usuario;
     private String nombre;
     private String descripcion;
     private String token;
     private Date fechaInicio;
     private Date fechaFin;
     private String estado;
     private Set<Aplicacion> aplicacions = new HashSet<Aplicacion>(0);
     private Set<Examentienepregunta> examentienepreguntas = new HashSet<Examentienepregunta>(0);

    public Examen() {
    }

	
    public Examen(Categoria categoria, Usuario usuario, String nombre, String descripcion, String token, Date fechaInicio, Date fechaFin, String estado) {
        this.categoria = categoria;
        this.usuario = usuario;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.token = token;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.estado = estado;
    }
    public Examen(Categoria categoria, Usuario usuario, String nombre, String descripcion, String token, Date fechaInicio, Date fechaFin, String estado, Set<Aplicacion> aplicacions, Set<Examentienepregunta> examentienepreguntas) {
       this.categoria = categoria;
       this.usuario = usuario;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.token = token;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.estado = estado;
       this.aplicacions = aplicacions;
       this.examentienepreguntas = examentienepreguntas;
    }
   
    public Integer getIdExamen() {
        return this.idExamen;
    }
    
    public void setIdExamen(Integer idExamen) {
        this.idExamen = idExamen;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<Aplicacion> getAplicacions() {
        return this.aplicacions;
    }
    
    public void setAplicacions(Set<Aplicacion> aplicacions) {
        this.aplicacions = aplicacions;
    }
    public Set<Examentienepregunta> getExamentienepreguntas() {
        return this.examentienepreguntas;
    }
    
    public void setExamentienepreguntas(Set<Examentienepregunta> examentienepreguntas) {
        this.examentienepreguntas = examentienepreguntas;
    }




}


