package mx.edu.utez.entity;
// Generated 21-jun-2018 22:32:54 by Hibernate Tools 4.3.1



/**
 * Examentienepregunta generated by hbm2java
 */
public class Examentienepregunta  implements java.io.Serializable {


     private Integer idExamenPregunta;
     private Examen examen;
     private Pregunta pregunta;

    public Examentienepregunta() {
    }

    public Examentienepregunta(Examen examen, Pregunta pregunta) {
       this.examen = examen;
       this.pregunta = pregunta;
    }
   
    public Integer getIdExamenPregunta() {
        return this.idExamenPregunta;
    }
    
    public void setIdExamenPregunta(Integer idExamenPregunta) {
        this.idExamenPregunta = idExamenPregunta;
    }
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }




}


