package mx.edu.utez.entity;
// Generated 21-jun-2018 22:32:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private Integer idPregunta;
     private Categoria categoria;
     private String pregunta;
     private Set<Respuesta> respuestas = new HashSet<Respuesta>(0);
     private Set<Examentienepregunta> examentienepreguntas = new HashSet<Examentienepregunta>(0);

    public Pregunta() {
    }

	
    public Pregunta(Categoria categoria, String pregunta) {
        this.categoria = categoria;
        this.pregunta = pregunta;
    }
    public Pregunta(Categoria categoria, String pregunta, Set<Respuesta> respuestas, Set<Examentienepregunta> examentienepreguntas) {
       this.categoria = categoria;
       this.pregunta = pregunta;
       this.respuestas = respuestas;
       this.examentienepreguntas = examentienepreguntas;
    }
   
    public Integer getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(Integer idPregunta) {
        this.idPregunta = idPregunta;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }
    public Set<Respuesta> getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(Set<Respuesta> respuestas) {
        this.respuestas = respuestas;
    }
    public Set<Examentienepregunta> getExamentienepreguntas() {
        return this.examentienepreguntas;
    }
    
    public void setExamentienepreguntas(Set<Examentienepregunta> examentienepreguntas) {
        this.examentienepreguntas = examentienepreguntas;
    }




}


