package mx.edu.utez.entity;
// Generated 21-jun-2018 22:32:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Respuesta generated by hbm2java
 */
public class Respuesta  implements java.io.Serializable {


     private Integer idRespuesta;
     private Pregunta pregunta;
     private String respuesta;
     private byte correcta;
     private Set<Respuestausuario> respuestausuarios = new HashSet<Respuestausuario>(0);

    public Respuesta() {
    }

	
    public Respuesta(Pregunta pregunta, String respuesta, byte correcta) {
        this.pregunta = pregunta;
        this.respuesta = respuesta;
        this.correcta = correcta;
    }
    public Respuesta(Pregunta pregunta, String respuesta, byte correcta, Set<Respuestausuario> respuestausuarios) {
       this.pregunta = pregunta;
       this.respuesta = respuesta;
       this.correcta = correcta;
       this.respuestausuarios = respuestausuarios;
    }
   
    public Integer getIdRespuesta() {
        return this.idRespuesta;
    }
    
    public void setIdRespuesta(Integer idRespuesta) {
        this.idRespuesta = idRespuesta;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }
    public byte getCorrecta() {
        return this.correcta;
    }
    
    public void setCorrecta(byte correcta) {
        this.correcta = correcta;
    }
    public Set<Respuestausuario> getRespuestausuarios() {
        return this.respuestausuarios;
    }
    
    public void setRespuestausuarios(Set<Respuestausuario> respuestausuarios) {
        this.respuestausuarios = respuestausuarios;
    }




}


